// SIUAT Question Bank - Part 1 (BA, BBA, BCA, B.Com, B.Pharma)

export const QB_PART1 = {
"BA": [

  {q:"1. Read the following passage and answer the question that follows: \"The ancient Indian education system placed great emphasis on the holistic development of an individual. It was not merely about the acquisition of knowledge but also about the cultivation of values, ethics, and practical skills. The Gurukul system, where students lived with their teachers, fostered a deep bond between the guru and the shishya, ensuring that learning was not just intellectual but also experiential.\" What was the primary focus of the ancient Indian education system according to the passage?",opts:["Only intellectual knowledge","Holistic development including values and practical skills","Acquisition of wealth","Strict discipline without any freedom"],ans:1,sec:"Humanities",marks:1},
  {q:"2. Who is the current Secretary-General of the United Nations (as of 2024-2026)?",opts:["Ban Ki-moon","António Guterres","Kofi Annan","Kurt Waldheim"],ans:1,sec:"Humanities",marks:1},
  {q:"3. In a certain code, if 'INDIA' is written as 'KPFKC', then how is 'CHINA' written in the same code?",opts:["EJKPC","EJLPC","EJLQC","FJKPC"],ans:1,sec:"Humanities",marks:1},
  {q:"4. The average of 6 numbers is 15. If one number is removed, the average becomes 12. What is the removed number?",opts:["18","24","30","36"],ans:2,sec:"Humanities",marks:1},
  {q:"5. The famous treatise 'Arthashastra', which deals with statecraft and economic policy, was written by:",opts:["Kalidasa","Chanakya (Kautilya)","Banabhatta","Tulsidas"],ans:1,sec:"Humanities",marks:1},
  {q:"6. Choose the word that is the OPPOSITE in meaning to \"EPHEMERAL\":",opts:["Temporary","Fleeting","Permanent","Short-lived"],ans:2,sec:"Humanities",marks:1},
  {q:"7. The 'Kumbh Mela', one of the largest religious gatherings in the world, is held at which of the following river banks?",opts:["Ganga, Yamuna, and Godavari","Ganga, Yamuna, and Saraswati (Prayagraj)","Ganga, Brahmaputra, and Mahanadi","Narmada, Tapti, and Krishna"],ans:1,sec:"Humanities",marks:1},
  {q:"8. Statement: All historians are researchers. Some researchers are professors. Conclusions: I. Some historians are professors. II. Some professors are researchers. Which of the following is true?",opts:["Only I follows","Only II follows","Both I and II follow","Neither follows"],ans:1,sec:"Humanities",marks:1},
  {q:"9. A man buys a book for Rs. 250 and sells it for Rs. 300. What is his profit percentage?",opts:["10%","15%","20%","25%"],ans:2,sec:"Humanities",marks:1},
  {q:"10. The 'Doctrine of Separation of Powers' in modern political theory was most comprehensively proposed by:",opts:["John Locke","Jean-Jacques Rousseau","Montesquieu","Thomas Hobbes"],ans:2,sec:"Humanities",marks:1},
  {q:"11. Fill in the blank with the most appropriate word: \"The historian's account of the event was so ______ that even the most skeptical readers were convinced of its authenticity.\"",opts:["vague","convincing","ambiguous","superficial"],ans:1,sec:"Humanities",marks:1},
  {q:"12. Which of the following nations officially joined the BRICS grouping in January 2024 as a new full member?",opts:["Argentina","Egypt","Saudi Arabia","Iran"],ans:1,sec:"Humanities",marks:1},
  {q:"13. Pointing towards a lady, Raj said, \"She is the daughter of the only son of my grandfather.\" How is the lady related to Raj?",opts:["Sister","Mother","Cousin","Aunt"],ans:0,sec:"Humanities",marks:1},
  {q:"14. A student scored 72 marks out of 80 in History and 85 marks out of 100 in Geography. What is his aggregate percentage across both subjects?",opts:["85.0%","86.5%","87.2%","88.0%"],ans:2,sec:"Humanities",marks:1},
  {q:"15. The Harappan Civilization town of Lothal, known for its dockyard, is located in which present-day Indian state?",opts:["Gujarat","Rajasthan","Punjab","Maharashtra"],ans:0,sec:"Humanities",marks:1},
  {q:"16. Choose the correctly spelled word from the following options:",opts:["Occasion","Ocassion","Occassion","Ocasion"],ans:0,sec:"Humanities",marks:2},
  {q:"17. Which of the following is the highest civilian award in India?",opts:["Padma Vibhushan","Bharat Ratna","Padma Bhushan","Ashok Chakra"],ans:1,sec:"Humanities",marks:2},
  {q:"18. In a row of 40 students, Amit is 12th from the left. What is his rank from the right end?",opts:["27th","28th","29th","30th"],ans:2,sec:"Humanities",marks:2},
  {q:"19. If the cost price of 15 articles is equal to the selling price of 12 articles, what is the profit percentage?",opts:["20%","25%","30%","33.33%"],ans:1,sec:"Humanities",marks:2},
  {q:"20. The 'Mahabharata' epic is traditionally attributed to which ancient sage?",opts:["Valmiki","Ved Vyasa","Tulsidas","Kalidasa"],ans:1,sec:"Humanities",marks:2},
  {q:"21. Fill in the blank with the correct article: \"He is ______ honest civil servant who always follows the rules.\"",opts:["a","an","the","no article"],ans:1,sec:"Humanities",marks:2},
  {q:"22. The state with the longest coastline in India is:",opts:["Tamil Nadu","Andhra Pradesh","Gujarat","Maharashtra"],ans:2,sec:"Humanities",marks:2},
  {q:"23. If the letters of the word 'EDUCATION' are arranged in alphabetical order, which letter will be in the middle?",opts:["C","D","I","N"],ans:2,sec:"Humanities",marks:2},
  {q:"24. A sum of Rs. 4000 is invested at a simple interest rate of 5% per annum for 3 years. What is the total interest earned?",opts:["Rs. 500","Rs. 600","Rs. 700","Rs. 800"],ans:1,sec:"Humanities",marks:2},
  {q:"25. 'Satyagraha' as a political philosophy and method of non-violent resistance was first systematically articulated by:",opts:["Mahatma Gandhi","Jawaharlal Nehru","Subhas Chandra Bose","Bal Gangadhar Tilak"],ans:0,sec:"Humanities",marks:2},
  {q:"26. Choose the correct synonym for the word \"AMELIORATE\":",opts:["Worsen","Improve","Destroy","Ignore"],ans:1,sec:"Humanities",marks:2},
  {q:"27. The headquarters of the International Court of Justice (ICJ) is located in:",opts:["Geneva, Switzerland","New York, USA","The Hague, Netherlands","Paris, France"],ans:2,sec:"Humanities",marks:2},
  {q:"28. Find the next number in the series: 5, 12, 23, 38, 57, ?",opts:["72","76","80","85"],ans:2,sec:"Humanities",marks:2},
  {q:"29. The 'Directive Principles of State Policy' in the Indian Constitution are primarily borrowed from the Constitution of which country?",opts:["USA","Ireland","Australia","Canada"],ans:1,sec:"Humanities",marks:2},
  {q:"30. The famous ancient university of Nalanda was located in which present-day Indian state?",opts:["Uttar Pradesh","Bihar","Madhya Pradesh","West Bengal"],ans:1,sec:"Humanities",marks:2},
  {q:"31. Read the sentence and identify the grammatical error: \"The committee of ministers (A) have decided (B) to increase the budgetary allocation (C) for education (D).\"",opts:["A","B","C","D"],ans:1,sec:"Humanities",marks:3},
  {q:"32. Which of the following countries recently became the 4th nation to successfully land a spacecraft on the Moon in 2024?",opts:["China","Russia","India","Japan"],ans:3,sec:"Humanities",marks:3},
  {q:"33. In a family, A is the brother of B. C is the father of A. D is the mother of B. E is the sister of D. How is E related to B?",opts:["Aunt","Mother","Grandmother","Sister"],ans:0,sec:"Humanities",marks:3},
  {q:"34. 'Young India' and 'Harijan' were the prominent journals/periodicals started by which of the following leaders?",opts:["Jawaharlal Nehru","Subhas Chandra Bose","Mahatma Gandhi","Bal Gangadhar Tilak"],ans:2,sec:"Humanities",marks:3},
  {q:"35. The National Bird of India is:",opts:["Peacock","Eagle","Swan","Parrot"],ans:0,sec:"Humanities",marks:3},
  {q:"36. Fill in the blank with the correct preposition: \"The professor's lecture was so complex that most students could hardly make any sense ______ it.\"",opts:["of","to","for","with"],ans:0,sec:"Humanities",marks:3},
  {q:"37. The headquarters of the World Trade Organization (WTO) is located in:",opts:["Washington D.C., USA","Geneva, Switzerland","London, UK","Paris, France"],ans:1,sec:"Humanities",marks:3},
  {q:"38. If 'PAPER' is written as 'QBPFS' and 'BOOK' is written as 'CPPL', then how is 'PEN' written?",opts:["QFO","QFP","QFO","QGO"],ans:0,sec:"Humanities",marks:3},
  {q:"39. Which of the following rivers is known as the 'Sorrow of Bengal' due to its frequent and devastating floods?",opts:["Ganga","Damodar","Mahanadi","Brahmaputra"],ans:1,sec:"Humanities",marks:3},
  {q:"40. In the Indian Constitution, the Right to Education (RTE) was added as a fundamental right under which Article?",opts:["Article 14","Article 19","Article 21A","Article 30"],ans:2,sec:"Humanities",marks:3},
  {q:"41. Choose the word that is the OPPOSITE of \"FRUGAL\":",opts:["Economical","Thrifty","Extravagant","Miserly"],ans:2,sec:"Humanities",marks:4},
  {q:"42. The first woman President of India was:",opts:["Indira Gandhi","Pratibha Patil","Sarojini Naidu","Sonia Gandhi"],ans:1,sec:"Humanities",marks:4},
  {q:"43. Complete the analogy: 'Thermometer' is to 'Temperature' as 'Barometer' is to '______'.",opts:["Humidity","Wind speed","Atmospheric pressure","Rainfall"],ans:2,sec:"Humanities",marks:4},
  {q:"44. The French philosopher Auguste Comte is widely regarded as the founder of which academic discipline?",opts:["Psychology","Economics","Sociology","Political Science"],ans:2,sec:"Humanities",marks:4},
  {q:"45. The Indian state with the highest literacy rate as per the 2011 Census is:",opts:["Kerala","Tamil Nadu","Maharashtra","Punjab"],ans:0,sec:"Humanities",marks:4},
  {q:"46. Identify the grammatically correct sentence from the following options:",opts:["He has been working here since ten years.","He has been working here for ten years.","He has been working here from ten years.","He has been working here during ten years."],ans:1,sec:"Humanities",marks:4},
  {q:"47. Which of the following represents the 'Base Effect' in economics?",opts:["The effect of a low base in the previous year making current growth rates appear artificially high.","The minimum rate of interest set by the RBI.","The total value of goods and services produced.","The exchange rate between two currencies."],ans:0,sec:"Humanities",marks:4},
  {q:"48. Find the odd one out in the series: 1, 8, 27, 64, 125, 216, 343, 500.",opts:["125","216","343","500"],ans:3,sec:"Humanities",marks:4},
  {q:"49. The 'Neolithic Revolution' in human history is associated with which major transformation in human society?",opts:["Invention of writing","Beginning of agriculture and domestication of animals","Industrialization","Formation of nation-states"],ans:1,sec:"Humanities",marks:4},
  {q:"50. The famous sculpture of 'Trimurti' (three-headed Shiva) is found in the rock-cut caves of:",opts:["Ajanta","Ellora","Elephanta","Badami"],ans:2,sec:"Humanities",marks:4},
],
"BBA": [

  {q:"1. A man bought an article for Rs. 400 and sold it at a profit of 25%. What was his selling price?",opts:["Rs. 450","Rs. 480","Rs. 500","Rs. 540"],ans:2,sec:"Business",marks:1},
  {q:"2. Choose the synonym of the word 'MAGNANIMOUS' from the options given below:",opts:["Selfish","Generous","Cruel","Narrow-minded"],ans:1,sec:"Business",marks:1},
  {q:"3. In a certain code, 'APPLE' is written as 'BQQMF'. How is 'MANGO' written in the same code?",opts:["NBOHS","NBOIP","NBOHP","MBOHS"],ans:2,sec:"Business",marks:1},
  {q:"4. Which of the following is the largest shareholder of the Reserve Bank of India (RBI) as per its ownership structure?",opts:["Government of India","Private Banks","Public Sector Banks","Foreign Institutional Investors"],ans:0,sec:"Business",marks:1},
  {q:"5. A train travels at a speed of 72 km/h. How many meters does it cover in 15 seconds?",opts:["200 m","250 m","300 m","400 m"],ans:2,sec:"Business",marks:1},
  {q:"6. Read the passage... What is the primary concern expressed in the passage regarding oil-importing countries?",opts:["They are earning huge profits.","They are facing inflation and a widening current account deficit.","They have found alternative energy sources.","They are exporting more crude oil."],ans:1,sec:"Business",marks:1},
  {q:"7. The average of five consecutive odd numbers is 25. What is the largest number?",opts:["25","27","29","31"],ans:2,sec:"Business",marks:1},
  {q:"8. Fill in the blank... 'The CEO's ______ speech...'",opts:["lackluster","mundane","rousing","tedious"],ans:2,sec:"Business",marks:1},
  {q:"9. In a row of 50 students, Rahul is 15th from the left end. What is his rank from the right end?",opts:["34th","35th","36th","37th"],ans:2,sec:"Business",marks:1},
  {q:"10. Which of the following government schemes is primarily aimed at providing financial inclusion...",opts:["PM Awas Yojana","PM Jan Dhan Yojana","PM Mudra Yojana","PM Fasal Bima Yojana"],ans:1,sec:"Business",marks:1},
],
"BCA": [

  {q:"1. A car accelerates from rest at a constant rate of 2 m/s² for 10 seconds. What is the total distance covered by the car during this time?",opts:["50 m","100 m","200 m","20 m"],ans:1,sec:"Science",marks:1},
  {q:"2. The pH of a solution is 3. What is the concentration of H⁺ ions in the solution?",opts:["1 × 10⁻³ M","1 × 10³ M","3 M","1 × 10⁻¹¹ M"],ans:0,sec:"Science",marks:1},
  {q:"3. If the roots of the quadratic equation x² - 5x + 6 = 0 are α and β, then the value of α + β is:",opts:["5","-5","6","-6"],ans:0,sec:"Science",marks:1},
  {q:"4. A force of 10 N is applied on a 2 kg block kept on a frictionless horizontal surface. The work done by this force in moving the block through 5 meters is:",opts:["25 J","50 J","100 J","0 J"],ans:1,sec:"Science",marks:1},
  {q:"5. Which of the following elements has the highest electronegativity among the halogens?",opts:["Chlorine","Bromine","Iodine","Fluorine"],ans:3,sec:"Science",marks:1},
  {q:"6. The value of sin 30° + cos 60° is:",opts:["1","0.5","1.5","0"],ans:0,sec:"Science",marks:1},
  {q:"7. Two resistors of 4Ω and 6Ω are connected in series with a 10V battery. The current flowing through the circuit is:",opts:["2 A","1 A","5 A","10 A"],ans:1,sec:"Science",marks:1},
  {q:"8. The IUPAC name of the compound CH₃-CH₂-CH₂-OH is:",opts:["Propan-1-ol","Propan-2-ol","Butan-1-ol","Ethanol"],ans:0,sec:"Science",marks:1},
  {q:"9. The slope of the line passing through the points (1, 2) and (3, 8) is:",opts:["6","3","2","1/3"],ans:1,sec:"Science",marks:1},
  {q:"10. A ball of mass 0.5 kg is thrown vertically upwards with a velocity of 20 m/s. What is its kinetic energy at the highest point of its motion? (Take g = 10 m/s²)",opts:["100 J","50 J","0 J","200 J"],ans:2,sec:"Science",marks:1},
  {q:"11. In the periodic table, the elements of Group 1 are known as:",opts:["Halogens","Alkaline earth metals","Alkali metals","Noble gases"],ans:2,sec:"Science",marks:1},
  {q:"12. A card is drawn from a well-shuffled deck of 52 cards. What is the probability that it is a King?",opts:["1/52","1/13","1/4","4/13"],ans:1,sec:"Science",marks:1},
  {q:"13. The radius of curvature of a concave mirror is 40 cm. What is its focal length?",opts:["10 cm","20 cm","40 cm","80 cm"],ans:1,sec:"Science",marks:1},
  {q:"14. What is the hybridization of the carbon atom in methane (CH₄)?",opts:["sp","sp²","sp³","dsp²"],ans:2,sec:"Science",marks:1},
  {q:"15. The value of the integral ∫(2x) dx is:",opts:["x² + C","2x² + C","x + C","x²/2 + C"],ans:0,sec:"Science",marks:1},
  {q:"16. A ray of light travels from air (n=1) into a glass slab (n=1.5). If the angle of incidence is 30°, what is the approximate angle of refraction? (sin30° = 0.5, sin19.5° ≈ 0.33)",opts:["10.5°","19.5°","30°","45°"],ans:1,sec:"Science",marks:2},
  {q:"17. Which of the following is an exothermic reaction?",opts:["Photosynthesis","Dissolution of NH₄Cl in water","Burning of coal in air","Decomposition of CaCO₃"],ans:2,sec:"Science",marks:2},
  {q:"18. The center of the circle given by the equation x² + y² - 4x + 6y - 12 = 0 is:",opts:["(2, 3)","(-2, 3)","(2, -3)","(-2, -3)"],ans:2,sec:"Science",marks:2},
  {q:"19. The escape velocity from the surface of the Earth is approximately 11.2 km/s. If the mass of the Earth is doubled but the radius remains the same, the new escape velocity will become:",opts:["5.6 km/s","11.2 km/s","15.8 km/s","22.4 km/s"],ans:2,sec:"Science",marks:2},
  {q:"20. The functional group present in carboxylic acids is:",opts:["–OH","–CHO","–COOH","–COOC–"],ans:2,sec:"Science",marks:2},
  {q:"21. In a Geometric Progression (GP), the first term is 3 and the common ratio is 2. What is the 4th term?",opts:["12","24","48","6"],ans:1,sec:"Science",marks:2},
  {q:"22. A simple pendulum completes 20 oscillations in 40 seconds. What is its time period?",opts:["0.5 s","2 s","4 s","20 s"],ans:1,sec:"Science",marks:2},
  {q:"23. How many moles of oxygen atoms are present in 1 mole of H₂SO₄?",opts:["1","2","3","4"],ans:3,sec:"Science",marks:2},
  {q:"24. What is the derivative of sin x with respect to x?",opts:["-cos x","cos x","sec² x","-sin x"],ans:1,sec:"Science",marks:2},
  {q:"25. The angular velocity of a particle moving in a circular path of radius 2m with a linear speed of 10 m/s is:",opts:["20 rad/s","12 rad/s","8 rad/s","5 rad/s"],ans:3,sec:"Science",marks:2},
  {q:"26. If the temperature of a gas is increased at constant pressure, its volume will:",opts:["Decrease","Increase","Remain constant","First decrease then increase"],ans:1,sec:"Science",marks:2},
  {q:"27. The value of log₂(32) is:",opts:["2","3","4","5"],ans:3,sec:"Science",marks:2},
  {q:"28. A transformer has 200 turns in the primary coil and 50 turns in the secondary coil. If the input voltage is 220 V, the output voltage is:",opts:["880 V","55 V","220 V","110 V"],ans:1,sec:"Science",marks:2},
  {q:"29. The number of electrons present in the valence shell of nitrogen (atomic number 7) is:",opts:["2","3","5","7"],ans:2,sec:"Science",marks:2},
  {q:"30. If A and B are two events such that P(A) = 0.4 and P(B) = 0.5, and they are mutually exclusive, then P(A ∪ B) is:",opts:["0.1","0.9","0.2","0.0"],ans:1,sec:"Science",marks:2},
  {q:"31. According to Kepler’s third law of planetary motion, the square of the time period (T) of a planet is directly proportional to:",opts:["Its mass","The radius of its orbit (R)","The cube of the semi-major axis (R³)","The square of the radius (R²)"],ans:2,sec:"Science",marks:3},
  {q:"32. A solution has 20g of glucose dissolved in 180g of water. The mass percentage of glucose in the solution is:",opts:["11.11%","20%","10%","12.5%"],ans:2,sec:"Science",marks:3},
  {q:"33. The sum of the first n natural numbers is 55, then the value of n is:",opts:["5","10","11","15"],ans:1,sec:"Science",marks:3},
  {q:"34. When white light passes through a glass prism, it splits into its constituent colors. This phenomenon is called:",opts:["Reflection","Refraction","Dispersion","Diffraction"],ans:2,sec:"Science",marks:3},
  {q:"35. Which of the following is a strong electrolyte?",opts:["Acetic acid (CH₃COOH)","Sodium chloride (NaCl)","Sugar (C₁₂H₂₂O₁₁)","Water (H₂O)"],ans:1,sec:"Science",marks:3},
  {q:"36. The coefficient of x² in the expansion of (1 + x)⁵ is:",opts:["1","5","10","20"],ans:2,sec:"Science",marks:3},
  {q:"37. A body of mass 5 kg is lifted to a height of 10 m. What is the increase in its potential energy? (g = 10 m/s²)",opts:["50 J","500 J","1000 J","250 J"],ans:1,sec:"Science",marks:3},
  {q:"38. The process in which a solid directly changes into a gas without passing through the liquid state is called:",opts:["Condensation","Evaporation","Sublimation","Fusion"],ans:2,sec:"Science",marks:3},
  {q:"39. The modulus of the complex number 3 + 4i is:",opts:["5","7","25","1"],ans:0,sec:"Science",marks:3},
  {q:"40. The distance between two point masses is doubled. The gravitational force between them will become:",opts:["Double","Half","One-fourth","Four times"],ans:2,sec:"Science",marks:3},
  {q:"41. Which of the following is the correct formula of Epsom salt?",opts:["Na₂CO₃","MgSO₄·7H₂O","CaSO₄·2H₂O","CuSO₄·5H₂O"],ans:1,sec:"Science",marks:4},
  {q:"42. The area under the curve y = x² from x = 0 to x = 2 is:",opts:["4/3","8/3","3/4","2/3"],ans:1,sec:"Science",marks:4},
  {q:"43. The SI unit of electric charge is:",opts:["Ampere","Volt","Coulomb","Ohm"],ans:2,sec:"Science",marks:4},
  {q:"44. What is the molecularity of the reaction: 2HI → H₂ + I₂?",opts:["1","2","0","3"],ans:1,sec:"Science",marks:4},
  {q:"45. If the vectors A = (2i + 3j) and B = (4i + 6j) are given, then the angle between them is:",opts:["0°","30°","45°","90°"],ans:0,sec:"Science",marks:4},
  {q:"46. Which of the following statements about a magnetic field line is correct?",opts:["They always cross each other","They form closed continuous loops","They start at the South pole and end at the North pole","They travel only in straight lines"],ans:1,sec:"Science",marks:4},
  {q:"47. Which of the following is not a greenhouse gas?",opts:["CO₂","Methane (CH₄)","Nitrogen (N₂)","Chlorofluorocarbons (CFCs)"],ans:2,sec:"Science",marks:4},
  {q:"48. The order of the differential equation (d²y/dx²) + 3(dy/dx) + 2y = 0 is:",opts:["0","1","2","3"],ans:2,sec:"Science",marks:4},
  {q:"49. In a redox reaction, the substance that loses electrons is said to be:",opts:["Reduced","Oxidized","Neutralized","Precipitated"],ans:1,sec:"Science",marks:4},
  {q:"50. A particle is executing Simple Harmonic Motion (SHM) with amplitude 'A'. At what displacement from the mean position is its kinetic energy equal to its potential energy?",opts:["A","A/√2","A/2","2A"],ans:1,sec:"Science",marks:4},
],
"B.Com": [

  {q:"1. What is the accounting equation?",opts:["Assets = Liabilities + Capital","Assets = Liabilities - Capital","Assets = Capital - Liabilities","Assets + Liabilities = Capital"],ans:0,sec:"Commerce",marks:1},
  {q:"2. The main objective of financial management is to:",opts:["Maximize profits","Maximize shareholder wealth","Minimize costs","Maximize sales"],ans:1,sec:"Commerce",marks:1},
  {q:"3. The price elasticity of demand for a product is -2. If the price is increased by 10%, what will be the approximate change in quantity demanded?",opts:["5% increase","10% decrease","20% decrease","20% increase"],ans:2,sec:"Commerce",marks:1},
  {q:"4. The average marks of 15 students is 40. If one student's marks are incorrectly recorded as 50 instead of 35, what is the correct average?",opts:["38","39","40","41"],ans:1,sec:"Commerce",marks:1},
  {q:"5. Choose the correctly spelled word:",opts:["Comittee","Committee","Comitee","Commitee"],ans:1,sec:"Commerce",marks:1},
  {q:"6. In a certain code, 'BUSINESS' is written as 'CTJJOFTT'. How is 'MANAGER' written?",opts:["NBOBHFS","NBOBHFT","NBOCIFT","NBOCHFS"],ans:0,sec:"Commerce",marks:1},
  {q:"7. Depreciation is a process of:",opts:["Valuation of assets","Allocation of cost","Increasing the value of assets","Recording of expenses"],ans:1,sec:"Commerce",marks:1},
  {q:"8. Which of the following is a function of management according to Henry Fayol?",opts:["Planning, Organizing, Commanding, Coordinating, Controlling","Planning, Staffing, Directing, Controlling","Planning, Organizing, Leading, Controlling","Planning, Organizing, Staffing, Directing, Coordinating, Controlling"],ans:0,sec:"Commerce",marks:1},
  {q:"9. The law of diminishing marginal utility states that:",opts:["Total utility increases at a constant rate","Marginal utility decreases with each additional unit consumed","Marginal utility increases with each additional unit consumed","Total utility decreases after each unit"],ans:1,sec:"Commerce",marks:1},
  {q:"10. A shopkeeper gives a discount of 25% on an article marked at Rs. 800. What is the selling price?",opts:["Rs. 500","Rs. 550","Rs. 600","Rs. 650"],ans:2,sec:"Commerce",marks:1},
  {q:"11. Fill in the blank: \"The CEO's ______ decision to invest in renewable energy was widely appreciated by the board members.\"",opts:["imprudent","audacious","reckless","cautious"],ans:1,sec:"Commerce",marks:1},
  {q:"12. If 'A' is the brother of 'B', 'B' is the sister of 'C', and 'C' is the father of 'D', how is 'A' related to 'D'?",opts:["Uncle","Father","Brother","Grandfather"],ans:0,sec:"Commerce",marks:1},
  {q:"13. A company has current assets of Rs. 5,00,000 and current liabilities of Rs. 2,00,000. What is its current ratio?",opts:["1.5:1","2:1","2.5:1","3:1"],ans:2,sec:"Commerce",marks:1},
  {q:"14. The term 'SWOT Analysis' in business strategy stands for:",opts:["Strengths, Weaknesses, Opportunities, Threats","Strategies, Work, Outputs, Targets","Strengths, Weaknesses, Obstacles, Trends","Systems, Work, Operations, Technologies"],ans:0,sec:"Commerce",marks:1},
  {q:"15. Which of the following is a direct tax in India?",opts:["GST","Customs Duty","Income Tax","Excise Duty"],ans:2,sec:"Commerce",marks:1},
  {q:"16. Read the passage and answer: \"The recent increase in the repo rate by the Reserve Bank of India is expected to make borrowing costlier for businesses, thereby slowing down investment and consumption demand. However, it may also help in curbing inflationary pressures that have been persistent over the last few months.\" What is the primary purpose of increasing the repo rate according to the passage?",opts:["To boost investment","To reduce inflation","To increase consumption","To reduce borrowing costs"],ans:1,sec:"Commerce",marks:2},
  {q:"17. The formula for calculating the Cost of Goods Sold (COGS) is:",opts:["Opening Stock + Purchases - Closing Stock","Opening Stock - Purchases + Closing Stock","Sales - Gross Profit","Both A and C"],ans:3,sec:"Commerce",marks:2},
  {q:"18. According to Maslow's hierarchy of needs, which need is at the highest level?",opts:["Safety needs","Social needs","Self-actualization needs","Esteem needs"],ans:2,sec:"Commerce",marks:2},
  {q:"19. In economics, 'Gross Domestic Product (GDP)' is the total market value of:",opts:["All final goods and services produced within a country in a given period","All goods and services produced by the citizens of a country","All final goods and services produced by the citizens of a country","All intermediate goods produced within a country"],ans:0,sec:"Commerce",marks:2},
  {q:"20. The simple interest on a sum for 3 years at 8% per annum is Rs. 480. What is the principal?",opts:["Rs. 1500","Rs. 1800","Rs. 2000","Rs. 2400"],ans:2,sec:"Commerce",marks:2},
  {q:"21. Choose the antonym of the word 'VERBOSE':",opts:["Wordy","Concise","Lengthy","Loquacious"],ans:1,sec:"Commerce",marks:2},
  {q:"22. Find the odd one out in the series: 2, 5, 10, 17, 26, 37, 50, 66.",opts:["37","50","66","26"],ans:2,sec:"Commerce",marks:2},
  {q:"23. The assets that are expected to be converted into cash within one year are called:",opts:["Fixed assets","Current assets","Intangible assets","Fictitious assets"],ans:1,sec:"Commerce",marks:2},
  {q:"24. Which of the following is a characteristic of a good business plan?",opts:["Vague objectives","Unrealistic financial projections","Clear mission and vision","Lack of market analysis"],ans:2,sec:"Commerce",marks:2},
  {q:"25. The concept of 'Marginal Cost' refers to:",opts:["The cost of producing one additional unit","The total cost of production","The fixed cost of production","The average cost of production"],ans:0,sec:"Commerce",marks:2},
  {q:"26. The compound interest on Rs. 5000 at 10% per annum for 2 years is:",opts:["Rs. 1000","Rs. 1025","Rs. 1050","Rs. 1100"],ans:2,sec:"Commerce",marks:2},
  {q:"27. Fill in the blank with the correct preposition: \"The manager has complete control ______ the daily operations of the department.\"",opts:["on","over","at","with"],ans:1,sec:"Commerce",marks:2},
  {q:"28. Pointing to a photograph, a person said, \"He is the only son of my father's wife.\" How is the person related to the man in the photograph?",opts:["Father","Brother","Himself","Son"],ans:2,sec:"Commerce",marks:2},
  {q:"29. The accounting principle that requires recording expenses in the same period as the revenues they help to generate is called:",opts:["Matching principle","Revenue recognition principle","Cost principle","Conservatism principle"],ans:0,sec:"Commerce",marks:2},
  {q:"30. The 'Porter's Five Forces' model is used to analyze:",opts:["Macroeconomic environment","Industry competitiveness","Consumer behavior","Internal organizational structure"],ans:1,sec:"Commerce",marks:2},
  {q:"31. Which of the following is a measure to control inflation in an economy?",opts:["Reducing taxes","Increasing government spending","Increasing the repo rate","Decreasing the repo rate"],ans:2,sec:"Commerce",marks:3},
  {q:"32. A person buys an article for Rs. 400 and sells it at a profit of 12.5%. What is the selling price?",opts:["Rs. 420","Rs. 430","Rs. 440","Rs. 450"],ans:3,sec:"Commerce",marks:3},
  {q:"33. Identify the grammatically incorrect part: \"Neither the accountant nor the auditors (A) was able to find (B) the discrepancy in (C) the final balance sheet (D).\"",opts:["A","B","C","D"],ans:1,sec:"Commerce",marks:3},
  {q:"34. A man walks 15 meters towards the North, then turns right and walks 20 meters, then turns right again and walks 15 meters. How far is he from his starting point?",opts:["10 m","15 m","20 m","35 m"],ans:2,sec:"Commerce",marks:3},
  {q:"35. The difference between the book value and the market value of an asset is known as:",opts:["Depreciation","Appreciation","Revaluation","Amortization"],ans:2,sec:"Commerce",marks:3},
  {q:"36. According to the 'Principle of Scalar Chain' in management, communication should ideally flow through:",opts:["Directly between any two employees","The formal chain of command from top to bottom","Only horizontally at the same level","Through informal channels only"],ans:1,sec:"Commerce",marks:3},
  {q:"37. The value of the marginal propensity to consume (MPC) is 0.75. What is the value of the multiplier?",opts:["1.33","2.00","3.00","4.00"],ans:3,sec:"Commerce",marks:3},
  {q:"38. The following data shows the sales of a company for 5 years: 2019: 200, 2020: 250, 2021: 300, 2022: 350, 2023: 400. What is the average annual growth rate?",opts:["10%","15%","20%","25%"],ans:2,sec:"Commerce",marks:3},
  {q:"39. Choose the correct synonym for 'BURGEONING':",opts:["Declining","Growing rapidly","Stagnant","Shrinking"],ans:1,sec:"Commerce",marks:3},
  {q:"40. All managers are employees. Some employees are executives. Conclusions: I. Some managers are executives. II. Some executives are employees. Which follows?",opts:["Only I","Only II","Both I and II","Neither"],ans:1,sec:"Commerce",marks:3},
  {q:"41. The process of converting raw materials into finished goods is classified under which type of activity?",opts:["Primary activity","Secondary activity","Tertiary activity","Quaternary activity"],ans:1,sec:"Commerce",marks:4},
  {q:"42. Goodwill is classified as which type of asset?",opts:["Current asset","Tangible asset","Intangible asset","Liquid asset"],ans:2,sec:"Commerce",marks:4},
  {q:"43. The main aim of disinvestment in public sector undertakings is:",opts:["To increase government control","To reduce fiscal deficit and improve efficiency","To increase subsidies","To nationalize industries"],ans:1,sec:"Commerce",marks:4},
  {q:"44. If the GDP of a country is Rs. 10,000 crores and its population is 50 crores, what is the per capita GDP?",opts:["Rs. 200","Rs. 400","Rs. 500","Rs. 1000"],ans:0,sec:"Commerce",marks:4},
  {q:"45. Fill in the blank: \"The company's profits have ______ significantly over the last quarter due to increased operational efficiency.\"",opts:["diminished","plummeted","surged","stagnated"],ans:2,sec:"Commerce",marks:4},
  {q:"46. The book of accounts that records all the journal entries in a chronological order is called:",opts:["Ledger","Journal","Trial balance","Balance sheet"],ans:1,sec:"Commerce",marks:4},
  {q:"47. According to the 'Span of Control' principle in management:",opts:["A manager should supervise a very large number of subordinates","There is an optimum number of subordinates a manager can effectively supervise","The span of control is fixed at five subordinates","Managers should supervise only one subordinate"],ans:1,sec:"Commerce",marks:4},
  {q:"48. The break-even point in economics is the point where:",opts:["Total revenue is greater than total cost","Total revenue equals total cost","Total revenue is less than total cost","Marginal cost equals marginal revenue"],ans:1,sec:"Commerce",marks:4},
  {q:"49. Find the next number in the series: 3, 8, 18, 38, 78, ?",opts:["118","128","138","158"],ans:3,sec:"Commerce",marks:4},
  {q:"50. The reserve created by a company for a specific future liability, such as a legal dispute, is called:",opts:["General reserve","Capital reserve","Provision","Dividend reserve"],ans:2,sec:"Commerce",marks:4},
],
"B.Pharma": [

  {q:"1. Which of the following is the most abundant gas in the Earth's atmosphere?",opts:["Oxygen","Nitrogen","Carbon dioxide","Argon"],ans:1,sec:"Pharmacy",marks:1},
  {q:"2. The pH of a 0.01 M HCl solution is:",opts:["1","2","3","4"],ans:1,sec:"Pharmacy",marks:1},
  {q:"3. Which type of immunity is acquired by receiving pre-formed antibodies from an external source?",opts:["Active natural immunity","Active artificial immunity","Passive natural immunity","Passive artificial immunity"],ans:3,sec:"Pharmacy",marks:1},
  {q:"4. A concave mirror has a radius of curvature of 40 cm. Its focal length is:",opts:["10 cm","20 cm","40 cm","80 cm"],ans:1,sec:"Pharmacy",marks:1},
  {q:"5. Choose the correctly spelled word from the following options:",opts:["Ommision","Omission","Omision","Ommision"],ans:1,sec:"Pharmacy",marks:1},
  {q:"6. Which of the following elements has the highest electronegativity in the periodic table?",opts:["Chlorine","Oxygen","Fluorine","Nitrogen"],ans:2,sec:"Pharmacy",marks:1},
  {q:"7. The human heart has how many chambers?",opts:["2","3","4","5"],ans:2,sec:"Pharmacy",marks:1},
  {q:"8. A car accelerates uniformly from rest and travels 100 meters in 5 seconds. What is its acceleration?",opts:["4 m/s²","8 m/s²","10 m/s²","20 m/s²"],ans:1,sec:"Pharmacy",marks:1},
  {q:"9. Fill in the blank with the correct preposition: \"He is very fond ______ playing cricket in his free time.\"",opts:["for","of","to","with"],ans:1,sec:"Pharmacy",marks:1},
  {q:"10. The IUPAC name of CH₃-CH₂-CH₂-OH is:",opts:["Propan-1-ol","Propan-2-ol","Butan-1-ol","Ethanol"],ans:0,sec:"Pharmacy",marks:1},
  {q:"11. Which of the following is the main site of photosynthesis in a leaf?",opts:["Epidermis","Palisade mesophyll","Phloem","Xylem"],ans:1,sec:"Pharmacy",marks:1},
  {q:"12. The SI unit of electric charge is:",opts:["Ampere","Volt","Coulomb","Ohm"],ans:2,sec:"Pharmacy",marks:1},
  {q:"13. In a certain code language, if 'MOUSE' is written as 'NPVTF', then how is 'KEY' written?",opts:["LFZ","LFY","LDZ","KFZ"],ans:0,sec:"Pharmacy",marks:1},
  {q:"14. Which of the following is a strong electrolyte?",opts:["Glucose solution","Urea solution","Sodium chloride solution","Acetic acid solution"],ans:2,sec:"Pharmacy",marks:1},
  {q:"15. The hormone responsible for the regulation of blood sugar levels is:",opts:["Thyroxine","Insulin","Adrenaline","Estrogen"],ans:1,sec:"Pharmacy",marks:1},
  {q:"16. A transformer has 400 turns in the primary coil and 100 turns in the secondary coil. If the input voltage is 220 V, what is the output voltage?",opts:["55 V","110 V","220 V","880 V"],ans:0,sec:"Pharmacy",marks:2},
  {q:"17. Find the odd one out in the series: 3, 7, 15, 31, 63, 127, 255, 511.",opts:["63","127","255","All are correct (No odd one)"],ans:3,sec:"Pharmacy",marks:2},
  {q:"18. Which of the following gas is evolved when baking soda is heated strongly?",opts:["Oxygen","Hydrogen","Carbon dioxide","Chlorine"],ans:2,sec:"Pharmacy",marks:2},
  {q:"19. The structural and functional unit of kidney is:",opts:["Neuron","Nephron","Alveolus","Villus"],ans:1,sec:"Pharmacy",marks:2},
  {q:"20. A man walks 10 meters towards the East, then turns left and walks 15 meters, then turns left again and walks 10 meters. How far is he from his starting point?",opts:["10 m","15 m","25 m","35 m"],ans:1,sec:"Pharmacy",marks:2},
  {q:"21. Which of the following is NOT a greenhouse gas?",opts:["Methane","Carbon dioxide","Nitrogen","Water vapor"],ans:2,sec:"Pharmacy",marks:2},
  {q:"22. The number of moles of oxygen atoms present in 1 mole of H₂SO₄ is:",opts:["1","2","3","4"],ans:3,sec:"Pharmacy",marks:2},
  {q:"23. The blood vessels that carry deoxygenated blood away from the heart are called:",opts:["Veins","Arteries","Pulmonary veins","Pulmonary arteries"],ans:3,sec:"Pharmacy",marks:2},
  {q:"24. The escape velocity from the surface of the Earth is approximately 11.2 km/s. If the mass of the Earth becomes four times, the escape velocity will become:",opts:["5.6 km/s","11.2 km/s","22.4 km/s","44.8 km/s"],ans:2,sec:"Pharmacy",marks:2},
  {q:"25. Identify the grammatically incorrect part in the sentence: \"Neither the teacher nor the students was present in the class.\"",opts:["Neither","nor","was","the class"],ans:2,sec:"Pharmacy",marks:2},
  {q:"26. Which of the following has the highest boiling point among the given 1M aqueous solutions?",opts:["Sugar","Urea","Sodium chloride (NaCl)","Magnesium chloride (MgCl₂)"],ans:3,sec:"Pharmacy",marks:2},
  {q:"27. The process of formation of a new individual from the vegetative parts of a parent plant is called:",opts:["Sexual reproduction","Spore formation","Vegetative propagation","Budding"],ans:2,sec:"Pharmacy",marks:2},
  {q:"28. A ray of light traveling from air (n=1) enters water (n=1.33) at an angle of incidence of 30°. What is the approximate angle of refraction? (sin 30° = 0.5, sin 22° ≈ 0.37)",opts:["10°","15°","22°","30°"],ans:2,sec:"Pharmacy",marks:2},
  {q:"29. If A is the father of B, and B is the sister of C, and C is the mother of D, how is A related to D?",opts:["Grandfather","Maternal grandfather","Father","Uncle"],ans:1,sec:"Pharmacy",marks:2},
  {q:"30. The functional group present in a carboxylic acid is:",opts:["–OH","–CHO","–COOH","–COOC–"],ans:2,sec:"Pharmacy",marks:2},
  {q:"31. The enzyme that helps in the digestion of proteins in the stomach is:",opts:["Amylase","Lipase","Pepsin","Trypsin"],ans:2,sec:"Pharmacy",marks:3},
  {q:"32. Two resistors of 6Ω and 12Ω are connected in parallel. Their equivalent resistance is:",opts:["2Ω","4Ω","6Ω","18Ω"],ans:1,sec:"Pharmacy",marks:3},
  {q:"33. Choose the word that is the OPPOSITE of \"CRUEL\":",opts:["Harsh","Kind","Severe","Angry"],ans:1,sec:"Pharmacy",marks:3},
  {q:"34. The process of rusting of iron is an example of:",opts:["Oxidation","Reduction","Sublimation","Distillation"],ans:0,sec:"Pharmacy",marks:3},
  {q:"35. The part of the brain that controls balance and coordination of the body is:",opts:["Cerebrum","Cerebellum","Medulla oblongata","Hypothalamus"],ans:1,sec:"Pharmacy",marks:3},
  {q:"36. The power of a lens is -2.0 D. What is the nature and focal length of the lens?",opts:["Convex, 50 cm","Concave, 50 cm","Convex, -50 cm","Concave, -50 cm"],ans:1,sec:"Pharmacy",marks:3},
  {q:"37. Which of the following is a primary pollutant?",opts:["Smog","Nitric oxide (NO)","Ozone (O₃)","Peroxyacyl nitrates (PAN)"],ans:1,sec:"Pharmacy",marks:3},
  {q:"38. In a cross between a pure tall plant (TT) and a pure dwarf plant (tt), the genotype of the F1 generation will be:",opts:["TT","tt","Tt","TtTt"],ans:2,sec:"Pharmacy",marks:3},
  {q:"39. The speed of sound in air is approximately 340 m/s. If the frequency of a sound wave is 680 Hz, what is its wavelength?",opts:["0.5 m","1.0 m","2.0 m","4.0 m"],ans:0,sec:"Pharmacy",marks:3},
  {q:"40. The atomic number of an element is 17. The number of electrons in its valence shell is:",opts:["5","7","8","17"],ans:1,sec:"Pharmacy",marks:3},
  {q:"41. The largest gland in the human body is:",opts:["Thyroid","Pancreas","Pituitary","Liver"],ans:3,sec:"Pharmacy",marks:4},
  {q:"42. The value of sin² 45° + cos² 45° is:",opts:["0","0.5","1","2"],ans:2,sec:"Pharmacy",marks:4},
  {q:"43. Fill in the blank: \"I have been waiting here ______ 2 hours.\"",opts:["since","for","from","by"],ans:1,sec:"Pharmacy",marks:4},
  {q:"44. Which of the following hybridization is exhibited by carbon in methane (CH₄)?",opts:["sp","sp²","sp³","dsp²"],ans:2,sec:"Pharmacy",marks:4},
  {q:"45. The membrane that surrounds the lungs is called:",opts:["Pericardium","Pleura","Peritoneum","Meninges"],ans:1,sec:"Pharmacy",marks:4},
  {q:"46. A body of mass 2 kg is lifted to a height of 5 meters. What is the increase in its potential energy? (g = 10 m/s²)",opts:["10 J","50 J","100 J","200 J"],ans:2,sec:"Pharmacy",marks:4},
  {q:"47. Which of the following is used as an antacid to neutralize excess stomach acid?",opts:["Sodium chloride","Sodium bicarbonate","Sodium hydroxide","Hydrochloric acid"],ans:1,sec:"Pharmacy",marks:4},
  {q:"48. The chromosomal theory of inheritance was proposed by:",opts:["Darwin","Mendel","Sutton and Boveri","Lamarck"],ans:2,sec:"Pharmacy",marks:4},
  {q:"49. Find the next number in the series: 1, 8, 27, 64, 125, ?",opts:["144","169","196","216"],ans:3,sec:"Pharmacy",marks:4},
  {q:"50. The work done in moving a charge of 5 coulombs across a potential difference of 10 volts is:",opts:["2 J","5 J","10 J","50 J"],ans:3,sec:"Pharmacy",marks:4},
],
};
