// SIUAT Question Bank - Part 2 (B.Sc, B.Tech, Diploma, LLB, Ph.D)

export const QB_PART2 = {
"B.Sc": [

  {q:"1. A car accelerates uniformly from rest at 3 m/s² for 8 seconds. What is the total distance traveled by the car?",opts:["72 m","96 m","48 m","24 m"],ans:1,sec:"Science",marks:1},
  {q:"2. The pH of a solution is 4. What is the concentration of H⁺ ions in moles per liter?",opts:["1 × 10⁴","1 × 10⁻⁴","4 × 10⁻¹","1 × 10⁻¹⁰"],ans:1,sec:"Science",marks:1},
  {q:"3. If the sum of the roots of the quadratic equation x² - 8x + k = 0 is 8, what is the value of k if the product of the roots is 15?",opts:["8","15","-15","7"],ans:1,sec:"Science",marks:1},
  {q:"4. Choose the correctly spelled word from the following options:",opts:["Acommodate","Accomodate","Accommodate","Acomodate"],ans:2,sec:"Science",marks:1},
  {q:"5. A 10 kg object is lifted to a height of 6 meters. What is the gain in its potential energy? (Take g = 10 m/s²)",opts:["600 J","60 J","6000 J","100 J"],ans:0,sec:"Science",marks:1},
  {q:"6. Which of the following is the IUPAC name of the compound CH₃-CH₂-COOH?",opts:["Propanoic acid","Ethanoic acid","Butanoic acid","Propanal"],ans:0,sec:"Science",marks:1},
  {q:"7. In a certain code, 'BAT' is written as '2012' (B=2, A=1, T=20). How will 'MAN' be written in the same code?",opts:["13114","13113","14113","14114"],ans:0,sec:"Science",marks:1},
  {q:"8. The derivative of cos x with respect to x is:",opts:["sin x","-sin x","sec² x","-cos x"],ans:1,sec:"Science",marks:1},
  {q:"9. Two resistors of 6Ω and 12Ω are connected in parallel with a 12V battery. The total current drawn from the battery is:",opts:["1 A","2 A","3 A","4 A"],ans:2,sec:"Science",marks:1},
  {q:"10. What is the hybridization state of the carbon atom in ethene (C₂H₄)?",opts:["sp","sp²","sp³","sp³d"],ans:1,sec:"Science",marks:1},
  {q:"11. A card is drawn randomly from a well-shuffled deck of 52 playing cards. What is the probability that the card drawn is either a Queen or a red card?",opts:["7/13","1/2","4/13","1/13"],ans:0,sec:"Science",marks:1},
  {q:"12. Find the wrong number in the series: 3, 7, 15, 31, 65, 127.",opts:["7","15","65","127"],ans:2,sec:"Science",marks:1},
  {q:"13. A convex lens has a focal length of 15 cm. An object is placed at 30 cm from the lens. What is the nature and position of the image formed?",opts:["Real, inverted, and at 30 cm on the other side","Virtual, erect, and at 15 cm","Real, inverted, and at 15 cm on the other side","Virtual, inverted, and at 30 cm"],ans:0,sec:"Science",marks:1},
  {q:"14. In a reaction, 16 grams of methane (CH₄) is completely burnt in excess oxygen. How many grams of carbon dioxide (CO₂) is produced?",opts:["22 g","44 g","66 g","88 g"],ans:1,sec:"Science",marks:1},
  {q:"15. Fill in the blank: \"The manager, along with his employees, ______ going to attend the conference scheduled for tomorrow morning.\"",opts:["are","is","were","have"],ans:1,sec:"Science",marks:1},
  {q:"16. What is the slope of the line passing through the points (-2, 5) and (4, -7)?",opts:["2","-2","1/2","-1/2"],ans:1,sec:"Science",marks:2},
  {q:"17. The escape velocity of a planet depends upon which of the following two factors directly?",opts:["Mass and radius of the planet","Mass of the object and radius","Density and temperature","Gravity and atmospheric pressure"],ans:0,sec:"Science",marks:2},
  {q:"18. Which element among the following belongs to the 3rd period and 17th group (halogens) of the modern periodic table?",opts:["Fluorine","Chlorine","Bromine","Iodine"],ans:1,sec:"Science",marks:2},
  {q:"19. Statement: All pens are books. All books are boxes. Conclusions: I. All pens are boxes. II. Some boxes are pens.",opts:["Only I follows","Only II follows","Both I and II follow","Neither follows"],ans:2,sec:"Science",marks:2},
  {q:"20. The integral of 4x³ with respect to x is:",opts:["x⁴ + C","4x⁴ + C","12x² + C","x⁴/4 + C"],ans:0,sec:"Science",marks:2},
  {q:"21. A ray of light traveling from air (n=1) strikes a glass surface (n=1.6) at an angle of incidence of 30°. What is the sine of the angle of refraction (sin r)?",opts:["0.3125","0.5","0.625","0.8"],ans:0,sec:"Science",marks:2},
  {q:"22. Choose the antonym of the word \"MEAGER\" from the given options:",opts:["Plentiful","Scarce","Insufficient","Limited"],ans:0,sec:"Science",marks:2},
  {q:"23. The number of moles of oxygen atoms present in 49 grams of H₂SO₄ is:",opts:["1 mole","2 moles","3 moles","4 moles"],ans:1,sec:"Science",marks:2},
  {q:"24. Direction Sense: Shyam walks 5 km towards the East. He turns right and walks 3 km. He then turns right again and walks 5 km. How far is he from his starting point?",opts:["13 km","5 km","3 km","8 km"],ans:2,sec:"Science",marks:2},
  {q:"25. A string of a musical instrument vibrates with a frequency of 200 Hz. If the tension in the string is increased 4 times, the new frequency will become:",opts:["50 Hz","100 Hz","400 Hz","800 Hz"],ans:2,sec:"Science",marks:2},
  {q:"26. Which of the following is NOT a greenhouse gas responsible for global warming?",opts:["Methane (CH₄)","Nitrogen (N₂)","Carbon dioxide (CO₂)","Water vapor (H₂O)"],ans:1,sec:"Science",marks:2},
  {q:"27. If log₁₀(1000) = x, then the value of x is:",opts:["2","3","4","10"],ans:1,sec:"Science",marks:2},
  {q:"28. Fill in the blank with the correct preposition: \"He apologized ______ the teacher ______ coming late to the class.\"",opts:["to, for","for, to","with, for","at, from"],ans:0,sec:"Science",marks:2},
  {q:"29. Identify the part of speech of the underlined word in the sentence: \"She quickly finished her homework before the dinner.\"",opts:["Adjective","Adverb","Verb","Noun"],ans:1,sec:"Science",marks:2},
  {q:"30. The first term of a Geometric Progression (GP) is 4 and the common ratio is 3. What is the 5th term of this GP?",opts:["108","324","972","256"],ans:1,sec:"Science",marks:2},
  {q:"31. A transformer has 500 turns in the primary coil and 100 turns in the secondary coil. If the input voltage is 220 V, what is the output voltage?",opts:["44 V","1100 V","55 V","220 V"],ans:0,sec:"Science",marks:3},
  {q:"32. In the chemical reaction: 2Mg + O₂ → 2MgO, what is the oxidizing agent?",opts:["Mg","O₂","MgO","Both Mg and O₂"],ans:1,sec:"Science",marks:3},
  {q:"33. The value of sin² 30° + cos² 30° is:",opts:["0","1/2","1","3/2"],ans:2,sec:"Science",marks:3},
  {q:"34. Arrange the following words in a logical sequence (from smallest to largest): 1. Elephant, 2. Ant, 3. Dog, 4. Lion.",opts:["2, 3, 4, 1","2, 4, 3, 1","3, 2, 4, 1","2, 3, 1, 4"],ans:0,sec:"Science",marks:3},
  {q:"35. A particle executes Simple Harmonic Motion (SHM) with an amplitude of 0.1 m. What is the maximum displacement of the particle from its mean position?",opts:["0.05 m","0.2 m","0.1 m","0 m"],ans:2,sec:"Science",marks:3},
  {q:"36. Which of the following aqueous solutions has the highest boiling point? (Assume all are 1M)",opts:["Sugar solution","Urea solution","Sodium chloride solution (NaCl)","Magnesium chloride solution (MgCl₂)"],ans:3,sec:"Science",marks:3},
  {q:"37. Find the next number in the series: 1, 4, 9, 16, 25, ?",opts:["30","35","36","49"],ans:2,sec:"Science",marks:3},
  {q:"38. Choose the grammatically correct sentence:",opts:["The data proves that the theory is wrong.","The data prove that the theory is wrong.","The data have prove that the theory wrong.","The data is proving the theory wrong."],ans:0,sec:"Science",marks:3},
  {q:"39. The focal length of a concave mirror is 20 cm. An object is placed at 60 cm from the mirror. The magnification produced is:",opts:["-1/2","-2","+1/2","+2"],ans:0,sec:"Science",marks:3},
  {q:"40. When sodium bicarbonate (NaHCO₃) is heated strongly, it decomposes into sodium carbonate, water, and a gas. The gas evolved is:",opts:["Oxygen","Carbon dioxide","Hydrogen","Chlorine"],ans:1,sec:"Science",marks:3},
  {q:"41. The simple interest on a sum for 3 years at 5% per annum is Rs. 600. What is the principal amount?",opts:["Rs. 3,000","Rs. 4,000","Rs. 5,000","Rs. 6,000"],ans:1,sec:"Science",marks:4},
  {q:"42. In a certain code language, 'FATHER' is written as 'GBUIFS'. How is 'MOTHER' written in the same language?",opts:["NPSFIS","NPUIFS","NQUIFS","NRUIFS"],ans:1,sec:"Science",marks:4},
  {q:"43. The resistance of a wire is R. If its length is doubled and the area of cross-section is halved, what will be the new resistance?",opts:["R/4","R/2","2R","4R"],ans:3,sec:"Science",marks:4},
  {q:"44. Which of the following is an example of a strong acid?",opts:["Acetic acid (CH₃COOH)","Carbonic acid (H₂CO₃)","Hydrochloric acid (HCl)","Citric acid"],ans:2,sec:"Science",marks:4},
  {q:"45. The value of (1 + tan² θ) is equal to:",opts:["sec² θ","sin² θ","cot² θ","cosec² θ"],ans:0,sec:"Science",marks:4},
  {q:"46. A man is facing North. He turns 90° clockwise, then 180° anticlockwise, and then 90° clockwise. Which direction is he facing now?",opts:["North","East","South","West"],ans:2,sec:"Science",marks:4},
  {q:"47. The most electronegative element among the following is:",opts:["Sodium","Chlorine","Oxygen","Fluorine"],ans:3,sec:"Science",marks:4},
  {q:"48. Fill in the blank with the correct idiom: \"We should not judge a person by his appearance; it is unwise to ______.\"",opts:["hit the nail on the head","burn the midnight oil","judge a book by its cover","break the ice"],ans:2,sec:"Science",marks:4},
  {q:"49. The probability of getting exactly two heads when three fair coins are tossed simultaneously is:",opts:["1/2","3/8","1/4","1/8"],ans:1,sec:"Science",marks:4},
  {q:"50. The displacement of a particle is given by x = 2t² + 4t + 5. What is the velocity of the particle at t = 2 seconds?",opts:["8 m/s","10 m/s","12 m/s","14 m/s"],ans:2,sec:"Science",marks:4},
],
"B.Tech": [

  {q:"1. The SI unit of force is:",opts:["Joule","Newton","Watt","Pascal"],ans:1,sec:"Engineering",marks:1},
  {q:"2. The chemical formula of water is:",opts:["H₂O₂","H₂O","CO₂","NaCl"],ans:1,sec:"Engineering",marks:1},
  {q:"3. The value of sin 90° is:",opts:["0","1/2","1","√3/2"],ans:2,sec:"Engineering",marks:1},
  {q:"4. The SI unit of electric current is:",opts:["Volt","Ampere","Ohm","Coulomb"],ans:1,sec:"Engineering",marks:1},
  {q:"5. The atomic number of oxygen is:",opts:["6","7","8","16"],ans:2,sec:"Engineering",marks:1},
  {q:"6. The area of a circle with radius r is:",opts:["2πr","πr²","2πr²","πr"],ans:1,sec:"Engineering",marks:1},
  {q:"7. According to Ohm’s law, the relation between voltage V, current I, and resistance R is:",opts:["V = I + R","V = I × R","V = I − R","V = R / I"],ans:1,sec:"Engineering",marks:1},
  {q:"8. The pH of pure water at 25°C is:",opts:["0","5","7","14"],ans:2,sec:"Engineering",marks:1},
  {q:"9. The sum of the interior angles of a triangle is:",opts:["90°","180°","270°","360°"],ans:1,sec:"Engineering",marks:1},
  {q:"10. The speed of light in vacuum is approximately:",opts:["3 × 10⁶ m/s","3 × 10⁸ m/s","3 × 10⁴ m/s","3 × 10¹⁰ m/s"],ans:1,sec:"Engineering",marks:1},
  {q:"11. The chemical formula of sulfuric acid is:",opts:["H₂SO₃","H₂SO₄","HCl","HNO₃"],ans:1,sec:"Engineering",marks:1},
  {q:"12. The square root of 144 is:",opts:["10","11","12","14"],ans:2,sec:"Engineering",marks:1},
  {q:"13. Newton’s third law of motion is also known as the law of:",opts:["Inertia","Acceleration","Action and Reaction","Gravitation"],ans:2,sec:"Engineering",marks:1},
  {q:"14. The symbol of the element sodium is:",opts:["S","Na","So","N"],ans:1,sec:"Engineering",marks:1},
  {q:"15. If x + 5 = 12, then x is:",opts:["5","6","7","8"],ans:2,sec:"Engineering",marks:1},
  {q:"16. The unit of electrical resistance is:",opts:["Volt","Ampere","Ohm","Watt"],ans:2,sec:"Engineering",marks:2},
  {q:"17. The gas used by plants during photosynthesis is:",opts:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"],ans:1,sec:"Engineering",marks:2},
  {q:"18. The value of 25% of 100 is:",opts:["20","25","30","50"],ans:1,sec:"Engineering",marks:2},
  {q:"19. The formula for kinetic energy is:",opts:["mgh","½mv²","mv²","½mgh"],ans:1,sec:"Engineering",marks:2},
  {q:"20. The hardest natural substance known is:",opts:["Iron","Quartz","Diamond","Graphite"],ans:2,sec:"Engineering",marks:2},
  {q:"21. The mean of the numbers 2, 4, and 6 is:",opts:["3","4","5","6"],ans:1,sec:"Engineering",marks:2},
  {q:"22. The SI unit of power is:",opts:["Joule","Newton","Watt","Ampere"],ans:2,sec:"Engineering",marks:2},
  {q:"23. Which of the following is a noble gas?",opts:["Oxygen","Nitrogen","Neon","Hydrogen"],ans:2,sec:"Engineering",marks:2},
  {q:"24. The value of π (pi) is approximately:",opts:["2.14","3.14","4.14","3.41"],ans:1,sec:"Engineering",marks:2},
  {q:"25. The acceleration due to gravity on Earth is approximately:",opts:["8.9 m/s²","9.8 m/s²","10.8 m/s²","98 m/s²"],ans:1,sec:"Engineering",marks:2},
  {q:"26. The common name of sodium bicarbonate is:",opts:["Washing soda","Baking soda","Caustic soda","Bleaching powder"],ans:1,sec:"Engineering",marks:2},
  {q:"27. The perimeter of a square with side 5 cm is:",opts:["10 cm","15 cm","20 cm","25 cm"],ans:2,sec:"Engineering",marks:2},
  {q:"28. The frequency of AC supply in India is:",opts:["30 Hz","50 Hz","60 Hz","100 Hz"],ans:1,sec:"Engineering",marks:2},
  {q:"29. Which of the following turns red litmus paper blue?",opts:["Acid","Base","Salt","Water"],ans:1,sec:"Engineering",marks:2},
  {q:"30. The HCF (Highest Common Factor) of 12 and 18 is:",opts:["2","3","6","12"],ans:2,sec:"Engineering",marks:2},
  {q:"31. The formula for gravitational potential energy near Earth’s surface is:",opts:["½mv²","mgh","F × d","ma"],ans:1,sec:"Engineering",marks:3},
  {q:"32. The chemical name of common salt is:",opts:["Sodium carbonate","Sodium chloride","Sodium bicarbonate","Sodium hydroxide"],ans:1,sec:"Engineering",marks:3},
  {q:"33. If 2x = 16, then x is:",opts:["6","7","8","9"],ans:2,sec:"Engineering",marks:3},
  {q:"34. A rainbow is formed due to:",opts:["Reflection only","Refraction and dispersion of sunlight","Diffraction only","Interference of light"],ans:1,sec:"Engineering",marks:3},
  {q:"35. Which of the following is a metal?",opts:["Carbon","Oxygen","Iron","Sulphur"],ans:2,sec:"Engineering",marks:3},
  {q:"36. The derivative of x² with respect to x is:",opts:["x","2x","2x²","x²/2"],ans:1,sec:"Engineering",marks:3},
  {q:"37. The process of rusting of iron is an example of:",opts:["Reduction","Oxidation","Neutralization","Decomposition"],ans:1,sec:"Engineering",marks:3},
  {q:"38. The value of tan 45° is:",opts:["0","1/2","1","√3"],ans:2,sec:"Engineering",marks:3},
  {q:"39. A transformer works on the principle of:",opts:["Ohm’s law","Electromagnetic induction","Newton’s law","Photoelectric effect"],ans:1,sec:"Engineering",marks:3},
  {q:"40. Isotopes of an element have the same:",opts:["Mass number","Atomic number","Number of neutrons","Number of nucleons"],ans:1,sec:"Engineering",marks:3},
  {q:"41. The value of log₁₀1 is:",opts:["0","1","10","100"],ans:0,sec:"Engineering",marks:4},
  {q:"42. The charge on an electron is:",opts:["Positive","Negative","Neutral","Zero"],ans:1,sec:"Engineering",marks:4},
  {q:"43. The slope of the line y = 3x + 2 is:",opts:["2","3","5","6"],ans:1,sec:"Engineering",marks:4},
  {q:"44. The LCM of 4 and 6 is:",opts:["2","6","12","24"],ans:2,sec:"Engineering",marks:4},
  {q:"45. Which of the following is a compound?",opts:["Oxygen","Hydrogen","Water","Nitrogen"],ans:2,sec:"Engineering",marks:4},
  {q:"46. The unit of work is:",opts:["Watt","Joule","Newton","Pascal"],ans:1,sec:"Engineering",marks:4},
  {q:"47. If a = 2 and b = 3, the value of a² + b² is:",opts:["10","13","15","25"],ans:1,sec:"Engineering",marks:4},
  {q:"48. The number of electrons in a neutral carbon atom is:",opts:["4","5","6","12"],ans:2,sec:"Engineering",marks:4},
  {q:"49. The value of cos 0° is:",opts:["0","1/2","1","√2/2"],ans:2,sec:"Engineering",marks:4},
  {q:"50. The process of separation of a solid from a solution is called:",opts:["Filtration","Evaporation","Distillation","Crystallization"],ans:3,sec:"Engineering",marks:4},
],
"Diploma": [

  {q:"1. What is the value of sin 30° + cos 60°?",opts:["0.5","1","1.5","2"],ans:1,sec:"General",marks:1},
  {q:"2. Which of the following is the chemical formula of sodium chloride?",opts:["NaCl","Na₂CO₃","NaHCO₃","NaOH"],ans:0,sec:"General",marks:1},
  {q:"3. Choose the correctly spelled word:",opts:["Accommodation","Acommodation","Accomodation","Acomodation"],ans:0,sec:"General",marks:1},
  {q:"4. In a certain code, if 'MOBILE' is written as 'NPCJMF', then how is 'PHONE' written?",opts:["QIPOF","QIPNF","QJPNE","QIPNE"],ans:0,sec:"General",marks:1},
  {q:"5. The average of 5 numbers is 20. If one number is removed, the average becomes 18. What is the removed number?",opts:["20","22","24","28"],ans:3,sec:"General",marks:1},
  {q:"6. The pH of a 0.001 M HCl solution is:",opts:["1","2","3","4"],ans:2,sec:"General",marks:1},
  {q:"7. The SI unit of force is:",opts:["Joule","Newton","Watt","Pascal"],ans:1,sec:"General",marks:1},
  {q:"8. Find the odd one out: 11, 17, 23, 29, 35, 41.",opts:["17","23","29","35"],ans:3,sec:"General",marks:1},
  {q:"9. The atomic number of carbon is:",opts:["4","6","8","10"],ans:1,sec:"General",marks:1},
  {q:"10. Fill in the blank: \"The professor's lecture was so ______ that the students could not understand anything.\"",opts:["clear","lucid","obscure","simple"],ans:2,sec:"General",marks:1},
  {q:"11. Pointing towards a lady, Raj said, \"She is the daughter of the only son of my grandfather.\" How is the lady related to Raj?",opts:["Sister","Mother","Cousin","Aunt"],ans:0,sec:"General",marks:1},
  {q:"12. The value of (x² - y²) when x=5 and y=3 is:",opts:["4","8","16","25"],ans:2,sec:"General",marks:1},
  {q:"13. The chemical formula of water is:",opts:["H₂O","CO₂","NH₃","CH₄"],ans:0,sec:"General",marks:1},
  {q:"14. Which of the following is a fundamental right under the Indian Constitution?",opts:["Right to property","Right to freedom of speech and expression","Right to work","Right to leisure"],ans:1,sec:"General",marks:1},
  {q:"15. A man walks 15 meters towards the North, then turns right and walks 20 meters, then turns right again and walks 15 meters. How far is he from his starting point?",opts:["10 m","15 m","20 m","35 m"],ans:2,sec:"General",marks:1},
  {q:"16. The velocity of a body is given by v = 2t² + 3t + 4. What is its acceleration at t = 2 seconds?",opts:["7 m/s²","11 m/s²","14 m/s²","18 m/s²"],ans:1,sec:"General",marks:2},
  {q:"17. Which of the following is the largest organ in the human body?",opts:["Liver","Heart","Lungs","Skin"],ans:3,sec:"General",marks:2},
  {q:"18. The derivative of x⁴ with respect to x is:",opts:["3x³","4x³","4x⁴","x⁴/4"],ans:1,sec:"General",marks:2},
  {q:"19. Which of the following is an example of a strong acid?",opts:["Acetic acid","Hydrochloric acid","Carbonic acid","Citric acid"],ans:1,sec:"General",marks:2},
  {q:"20. Choose the word that is the OPPOSITE of \"ABUNDANT\":",opts:["Plentiful","Scarce","Ample","Copious"],ans:1,sec:"General",marks:2},
  {q:"21. All dogs are animals. Some animals are pets. Conclusions: I. Some dogs are pets. II. Some pets are animals. Which is true?",opts:["Only I","Only II","Both I and II","Neither"],ans:1,sec:"General",marks:2},
  {q:"22. The simple interest on Rs. 4000 at 8% per annum for 3 years is:",opts:["Rs. 640","Rs. 720","Rs. 800","Rs. 960"],ans:3,sec:"General",marks:2},
  {q:"23. The SI unit of electric charge is:",opts:["Ampere","Volt","Coulomb","Ohm"],ans:2,sec:"General",marks:2},
  {q:"24. Which of the following is a greenhouse gas?",opts:["Oxygen","Nitrogen","Carbon dioxide","Argon"],ans:2,sec:"General",marks:2},
  {q:"25. Fill in the blank: \"The new policy will come ______ effect from next month.\"",opts:["into","in","at","on"],ans:0,sec:"General",marks:2},
  {q:"26. If 'A' is the brother of 'B', 'B' is the sister of 'C', and 'C' is the father of 'D', how is 'A' related to 'D'?",opts:["Uncle","Father","Brother","Grandfather"],ans:0,sec:"General",marks:2},
  {q:"27. The value of log₁₀(100) is:",opts:["1","2","3","10"],ans:1,sec:"General",marks:2},
  {q:"28. The chemical name of baking soda is:",opts:["Sodium carbonate","Sodium bicarbonate","Sodium chloride","Sodium hydroxide"],ans:1,sec:"General",marks:2},
  {q:"29. A convex lens of focal length 20 cm forms a real image of an object placed at 40 cm from the lens. What is the magnification?",opts:["-1","-2","+1","+2"],ans:0,sec:"General",marks:2},
  {q:"30. The average marks of 10 students is 35. If one student's marks are incorrectly recorded as 45 instead of 25, what is the correct average?",opts:["32","33","34","35"],ans:1,sec:"General",marks:2},
  {q:"31. Which of the following is NOT a type of computer virus?",opts:["Trojan horse","Worm","Malware","RAM"],ans:3,sec:"General",marks:3},
  {q:"32. The escape velocity from the surface of the Earth is approximately:",opts:["7.9 km/s","11.2 km/s","15.8 km/s","22.4 km/s"],ans:1,sec:"General",marks:3},
  {q:"33. Which of the following elements is a noble gas?",opts:["Oxygen","Nitrogen","Helium","Chlorine"],ans:2,sec:"General",marks:3},
  {q:"34. Find the next number in the series: 1, 4, 9, 16, 25, ?",opts:["30","32","34","36"],ans:3,sec:"General",marks:3},
  {q:"35. The full form of RAM is:",opts:["Random Access Memory","Read Access Memory","Random Action Memory","Readily Available Memory"],ans:0,sec:"General",marks:3},
  {q:"36. If the cost price of an article is Rs. 300 and the selling price is Rs. 375, what is the profit percentage?",opts:["20%","25%","30%","35%"],ans:1,sec:"General",marks:3},
  {q:"37. The process of converting a solid directly into gas is called:",opts:["Condensation","Evaporation","Sublimation","Deposition"],ans:2,sec:"General",marks:3},
  {q:"38. Identify the error in the sentence: \"The group of students (A) were (B) waiting for (C) their teacher (D).\"",opts:["A","B","C","D"],ans:1,sec:"General",marks:3},
  {q:"39. The sum of the first 10 natural numbers is:",opts:["45","50","55","60"],ans:2,sec:"General",marks:3},
  {q:"40. Which of the following is used to measure temperature?",opts:["Thermometer","Barometer","Hydrometer","Hygrometer"],ans:0,sec:"General",marks:3},
  {q:"41. A woman introduces a man as the son of the brother of her mother. How is the man related to the woman?",opts:["Uncle","Cousin","Brother","Nephew"],ans:1,sec:"General",marks:4},
  {q:"42. If sin θ = 3/5, then the value of cos θ is:",opts:["4/5","3/4","5/4","1/5"],ans:0,sec:"General",marks:4},
  {q:"43. The SI unit of power is:",opts:["Joule","Newton","Watt","Pascal"],ans:2,sec:"General",marks:4},
  {q:"44. Which of the following is a primary pollutant?",opts:["Ozone","Smog","Carbon monoxide","PAN"],ans:2,sec:"General",marks:4},
  {q:"45. Choose the synonym of the word \"DILIGENT\":",opts:["Lazy","Hardworking","Careless","Slow"],ans:1,sec:"General",marks:4},
  {q:"46. The angle between the hour hand and minute hand of a clock at 3:00 is:",opts:["45°","60°","90°","120°"],ans:2,sec:"General",marks:4},
  {q:"47. The chemical formula of methane is:",opts:["CH₄","C₂H₆","C₃H₈","C₄H₁₀"],ans:0,sec:"General",marks:4},
  {q:"48. The probability of getting a head in a single toss of a fair coin is:",opts:["0","0.25","0.5","1"],ans:2,sec:"General",marks:4},
  {q:"49. The headquarters of UNESCO is located in:",opts:["New York","Geneva","Paris","London"],ans:2,sec:"General",marks:4},
  {q:"50. The value of √(64) + √(36) is:",opts:["10","12","14","16"],ans:2,sec:"General",marks:4},
],
"LLB": [

  {q:"1. Which of the following is a tort?",opts:["Breach of trust","Defamation","Murder","Theft"],ans:1,sec:"Law",marks:1},
  {q:"2. The minimum age required to be the President of India is:",opts:["30 years","35 years","40 years","45 years"],ans:1,sec:"Law",marks:1},
  {q:"3. Choose the synonym of the word 'AUTHENTIC':",opts:["Fake","Genuine","Artificial","Doubtful"],ans:1,sec:"Law",marks:1},
  {q:"4. In a certain code, if 'LAW' is written as 'MBX', then how is 'ACT' written in the same code?",opts:["BDU","BDT","ADU","BCT"],ans:0,sec:"Law",marks:1},
  {q:"5. The average age of 5 students is 18 years. If one student leaves, the average becomes 17 years. What is the age of the student who left?",opts:["18 years","19 years","20 years","22 years"],ans:3,sec:"Law",marks:1},
  {q:"6. Under the Indian Contract Act, 1872, a contract is defined as:",opts:["An agreement enforceable by law","A promise made without consideration","An agreement not enforceable by law","A unilateral promise"],ans:0,sec:"Law",marks:1},
  {q:"7. Which of the following is a Fundamental Right guaranteed under the Indian Constitution?",opts:["Right to property","Right to freedom of speech and expression","Right to work","Right to leisure"],ans:1,sec:"Law",marks:1},
  {q:"8. Read the passage... What is the primary requirement for any infringement of the right to privacy...",opts:["It must be done by the executive only","It must pass the test of legality, necessity, and proportionality","It must be approved by the President","It must be limited to criminal cases"],ans:1,sec:"Law",marks:1},
  {q:"9. Which of the following is NOT a valid mode of discharge of a contract...",opts:["Performance","Agreement","Breach","Frustration"],ans:2,sec:"Law",marks:1},
  {q:"10. The President of India can promulgate an ordinance under which Article...",opts:["Article 123","Article 124","Article 125","Article 126"],ans:0,sec:"Law",marks:1},
  {q:"11. Identify the correctly spelled word:",opts:["Jurisprudence","Jurisprudence","Jurisprudence","Jurisprudence"],ans:0,sec:"Law",marks:1},
  {q:"12. The term 'voir dire' in legal proceedings means:",opts:["The final judgment of the court","The preliminary examination of a witness to determine competency","The written statement of the defendant","The order of the court for execution"],ans:1,sec:"Law",marks:1},
  {q:"13. The headquarters of the International Court of Justice (ICJ) is located at:",opts:["New York","Geneva","The Hague","Paris"],ans:2,sec:"Law",marks:1},
  {q:"14. A man goes 10 meters towards the North...",opts:["5 m","10 m","15 m","35 m"],ans:2,sec:"Law",marks:1},
  {q:"15. The sale of adulterated food items is punishable under...",opts:["Indian Penal Code, 1860","Consumer Protection Act, 2019","Food Safety and Standards Act, 2006","Both B and C"],ans:3,sec:"Law",marks:1},
  {q:"16. The National Green Tribunal (NGT) of India was established under which Act?",opts:["Environment Protection Act, 1986","National Green Tribunal Act, 2010","Water Prevention and Control of Pollution Act, 1974","Air Prevention and Control of Pollution Act, 1981"],ans:1,sec:"Law",marks:2},
  {q:"17. Fill in the blank: 'The lawyer's ______ argument...'",opts:["feeble","compelling","vague","ambiguous"],ans:1,sec:"Law",marks:2},
  {q:"18. Which of the following is a legal maxim meaning 'the thing speaks for itself'?",opts:["Res ipsa loquitur","Actus reus","Mens rea","Caveat emptor"],ans:0,sec:"Law",marks:2},
  {q:"19. The Union Budget of India for the year 2024-25 was presented...",opts:["1st February 2024","15th March 2024","1st April 2024","1st July 2024"],ans:0,sec:"Law",marks:2},
  {q:"20. In a criminal case, the burden of proof lies on:",opts:["The accused","The prosecution","The victim","The judge"],ans:1,sec:"Law",marks:2},
  {q:"21. The concept of 'Limited Liability' in a company means:",opts:["The liability of directors is unlimited","The liability of shareholders is limited to the unpaid amount on their shares","The liability of creditors is limited","The liability of employees is unlimited"],ans:1,sec:"Law",marks:2},
  {q:"22. The highest gallantry award in India during peacetime is:",opts:["Param Vir Chakra","Ashok Chakra","Mahavir Chakra","Kirti Chakra"],ans:1,sec:"Law",marks:2},
  {q:"23. Complete the analogy: 'Judge' is to 'Court' as 'Arbitrator' is to '______'.",opts:["Mediation","Arbitration","Tribunal","Conciliation"],ans:1,sec:"Law",marks:2},
  {q:"24. The simple interest on a sum of Rs. 6000 at 6% per annum for 2 years is:",opts:["Rs. 360","Rs. 480","Rs. 600","Rs. 720"],ans:3,sec:"Law",marks:2},
  {q:"25. The maximum punishment for defamation under the Indian Penal Code...",opts:["Simple imprisonment","Imprisonment for up to 2 years, or fine, or both","Imprisonment for up to 5 years","Life imprisonment"],ans:1,sec:"Law",marks:2},
  {q:"26. The right to constitutional remedies under Article 32 ... can be suspended during:",opts:["Any emergency","National emergency only","Financial emergency","President's rule"],ans:1,sec:"Law",marks:2},
  {q:"27. Choose the grammatically correct sentence:",opts:["The committee have decided to adjourn the meeting.","The committee has decided to adjourn the meeting.","The committee are decided to adjourn the meeting.","The committee is decide to adjourn the meeting."],ans:1,sec:"Law",marks:2},
  {q:"28. The 'Doctrine of Pleasure' ... is applicable to:",opts:["Civil servants holding office during the pleasure of the President/Governor","Judges of the Supreme Court","Members of Parliament","State Governors"],ans:0,sec:"Law",marks:2},
  {q:"29. The International Monetary Fund (IMF) has projected India's GDP growth rate ... at approximately:",opts:["5.0%","6.5%","7.0%","8.5%"],ans:2,sec:"Law",marks:2},
  {q:"30. Which of the following is an example of a valid offer...",opts:["A statement of intention","An invitation to offer","A promise to buy goods at a certain price communicated to a specific person","A mere declaration of price in a catalog"],ans:2,sec:"Law",marks:2},
  {q:"31. ... what constitutes 'constructive possession'?",opts:["Physical holding of the contraband","Power and intention to control the contraband","Knowledge of the contraband only","Being present at the place of recovery"],ans:1,sec:"Law",marks:3},
  {q:"32. Which of the following writs is issued ... to transfer a case ...?",opts:["Habeas Corpus","Mandamus","Certiorari","Quo Warranto"],ans:2,sec:"Law",marks:3},
  {q:"33. Which of the following countries is NOT a permanent member of the United Nations Security Council?",opts:["United Kingdom","China","Germany","Russia"],ans:2,sec:"Law",marks:3},
  {q:"34. Pointing towards a man, a woman said...",opts:["Mother","Aunt","Sister","Grandmother"],ans:0,sec:"Law",marks:3},
  {q:"35. The maxim 'Actus non facit reum nisi mens sit rea' means:",opts:["The act itself does not constitute guilt unless done with a guilty mind","The guilty mind alone is sufficient for punishment","The victim's consent is a defence","Ignorance of law is no excuse"],ans:0,sec:"Law",marks:3},
  {q:"36. The Goods and Services Tax (GST) in India was introduced on:",opts:["1st July 2016","1st July 2017","1st April 2017","1st January 2018"],ans:1,sec:"Law",marks:3},
  {q:"37. Choose the word that is the OPPOSITE of 'FRAUDULENT':",opts:["Honest","Deceitful","Corrupt","Tricky"],ans:0,sec:"Law",marks:3},
  {q:"38. The 'Limitation Act, 1963' ... general period ... for breach of contract is:",opts:["1 year","2 years","3 years","5 years"],ans:2,sec:"Law",marks:3},
  {q:"39. The number of times the President of India can dissolve the Lok Sabha is:",opts:["Once","Twice","As many times as deemed fit","Only with the Chief Justice's permission"],ans:2,sec:"Law",marks:3},
  {q:"40. A dishonest dealer claims to sell ... 960 grams ... profit percentage?",opts:["4.0%","4.17%","5.0%","6.0%"],ans:1,sec:"Law",marks:3},
  {q:"41. Fill in the blank ... acquitted the accused ______ all charges...",opts:["from","of","for","with"],ans:1,sec:"Law",marks:4},
  {q:"42. The 'Bail' under Criminal Procedure Code ... is primarily governed by:",opts:["Section 437 and 439","Section 300","Section 144","Section 125"],ans:0,sec:"Law",marks:4},
  {q:"43. Which of the following is a major source of revenue for the Government of India?",opts:["Income tax","GST","Customs duty","All of the above"],ans:3,sec:"Law",marks:4},
  {q:"44. Find the next number in the series: 4, 12, 36, 108, 324, ?",opts:["648","864","972","1296"],ans:2,sec:"Law",marks:4},
  {q:"45. Under the Hindu Succession Act ... a daughter is a Class-I heir...",opts:["Only if she is unmarried","Only if there is no son","As a coparcener with equal rights as a son","Only if the father dies intestate and has no wife"],ans:2,sec:"Law",marks:4},
  {q:"46. The famous 'Gang of Four' ... refers to:",opts:["Four judges who stayed the Ayodhya verdict","Four senior Supreme Court judges who held a press conference in 2018...","Four women judges appointed in 2020","Four Chief Justices appointed together"],ans:1,sec:"Law",marks:4},
  {q:"47. Identify the error in the sentence: 'The law professor ... along with his students were invited...'",opts:["A","B","C","D"],ans:2,sec:"Law",marks:4},
  {q:"48. The 'Caveat Emptor' principle means:",opts:["Let the seller beware","Let the buyer beware","Let the law take its course","Let the judge decide"],ans:1,sec:"Law",marks:4},
  {q:"49. The Chief Justice of India is appointed by the President under which Article...",opts:["Article 124(2)","Article 126","Article 217","Article 222"],ans:0,sec:"Law",marks:4},
  {q:"50. A sum of money doubles itself in 5 years at simple interest. What is the rate of interest per annum?",opts:["10%","15%","20%","25%"],ans:2,sec:"Law",marks:4},
],
"Ph.D": [

  {q:"1. Which type of sampling involves selecting every nth individual from a list?",opts:["Random sampling","Stratified sampling","Systematic sampling","Cluster sampling"],ans:2,sec:"Research",marks:1},
  {q:"2. The chemical formula of water is:",opts:["H₂O","CO₂","NaCl","HCl"],ans:0,sec:"Research",marks:1},
  {q:"3. In a code language, if 'STUDY' is written as 'TUV EZ' (actually +1 each), then how is 'PAPER' written?",opts:["QBQFS","QCPFS","QBQFT","QCPFT"],ans:0,sec:"Research",marks:1},
  {q:"4. A car travels 120 km in 2 hours. What is its average speed in km/h?",opts:["40","60","80","100"],ans:1,sec:"Research",marks:1},
  {q:"5. Read the passage and answer: \"The peer-review process is the cornerstone of academic publishing...\" What is the main purpose of the peer-review process according to the passage?",opts:["To delay scientific publications","To scrutinize research findings before dissemination","To increase the cost of publishing","To reduce the number of publications"],ans:1,sec:"Research",marks:1},
  {q:"6. What is the primary purpose of a literature review in research?",opts:["To list all books in the library","To summarize existing knowledge and identify research gaps","To prove the researcher's hypothesis","To collect raw data"],ans:1,sec:"Research",marks:1},
  {q:"7. The father of the Indian Constitution is:",opts:["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Sardar Patel"],ans:2,sec:"Research",marks:1},
  {q:"8. A null hypothesis (H₀) is a statement that:",opts:["There is a significant effect or relationship","There is no effect or relationship","The research design is flawed","The sample size is too small"],ans:1,sec:"Research",marks:1},
  {q:"9. Choose the correctly spelled word:",opts:["Occurence","Occurrence","Ocurrence","Occurence"],ans:1,sec:"Research",marks:1},
  {q:"10. Which of the following represents a 'ratio scale' of measurement?",opts:["Gender (Male/Female)","Temperature in Celsius","Income in Rupees","Education level (High School, Graduate, Postgraduate)"],ans:2,sec:"Research",marks:1},
  {q:"11. The national animal of India is:",opts:["Lion","Tiger","Elephant","Peacock"],ans:1,sec:"Research",marks:1},
  {q:"12. Pointing to a photograph, a man said, \"His father is the only son of my mother.\" How is the man in the photograph related to the speaker?",opts:["Son","Father","Brother","Nephew"],ans:0,sec:"Research",marks:1},
  {q:"13. The dependent variable in an experiment is:",opts:["The variable that is manipulated by the researcher","The variable that is measured to see the effect of manipulation","The variable that remains constant throughout","The variable that introduces bias"],ans:1,sec:"Research",marks:1},
  {q:"14. Which of the following is a greenhouse gas primarily responsible for global warming?",opts:["Oxygen","Nitrogen","Carbon dioxide","Argon"],ans:2,sec:"Research",marks:1},
  {q:"15. The average of 7 numbers is 24. If one number is excluded, the average becomes 22. What is the excluded number?",opts:["28","30","32","36"],ans:3,sec:"Research",marks:1},
  {q:"16. The famous book 'Discovery of India' was written by:",opts:["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Rabindranath Tagore"],ans:1,sec:"Research",marks:2},
  {q:"17. In research, the term 'validity' refers to:",opts:["The consistency of the measurement","The accuracy of the measurement (whether it measures what it claims to measure)","The sample size","The statistical test used"],ans:1,sec:"Research",marks:2},
  {q:"18. The capital of Australia is:",opts:["Sydney","Melbourne","Canberra","Brisbane"],ans:2,sec:"Research",marks:2},
  {q:"19. Complete the analogy: 'Thermometer' is to 'Temperature' as 'Barometer' is to '______'.",opts:["Humidity","Wind speed","Atmospheric pressure","Rainfall"],ans:2,sec:"Research",marks:2},
  {q:"20. The maximum punishment for defamation under the Indian Penal Code is:",opts:["Fine only","Imprisonment up to 2 years, or fine, or both","Imprisonment up to 5 years","Life imprisonment"],ans:1,sec:"Research",marks:2},
  {q:"21. 'Cronbach's Alpha' is a measure of:",opts:["Internal consistency reliability","Test-retest reliability","Inter-rater reliability","Validity"],ans:0,sec:"Research",marks:2},
  {q:"22. Which of the following is the smallest bone in the human body?",opts:["Femur","Stapes","Tibia","Humerus"],ans:1,sec:"Research",marks:2},
  {q:"23. Fill in the blank with the correct preposition: \"The research paper was submitted ______ the journal for publication.\"",opts:["to","for","at","on"],ans:0,sec:"Research",marks:2},
  {q:"24. The purpose of a pilot study is to:",opts:["Test the research instruments and procedures on a small scale","Collect final data for the main study","Publish the research findings","Select the final sample"],ans:0,sec:"Research",marks:2},
  {q:"25. The SI unit of force is:",opts:["Joule","Newton","Watt","Pascal"],ans:1,sec:"Research",marks:2},
  {q:"26. If 15 men can complete a work in 10 days, how many days will 25 men take to complete the same work?",opts:["4 days","6 days","8 days","10 days"],ans:1,sec:"Research",marks:2},
  {q:"27. Which of the following is an example of primary data?",opts:["An encyclopedia article","A survey questionnaire filled by respondents","A review article","A documentary film"],ans:1,sec:"Research",marks:2},
  {q:"28. The ozone layer depletion is primarily caused by:",opts:["Carbon dioxide","Methane","Chlorofluorocarbons (CFCs)","Nitrogen dioxide"],ans:2,sec:"Research",marks:2},
  {q:"29. Find the next number in the series: 2, 8, 18, 32, 50, ?",opts:["64","72","82","90"],ans:1,sec:"Research",marks:2},
  {q:"30. The 'Hawthorne Effect' in research refers to:",opts:["A statistical error in sampling","The phenomenon where subjects modify their behavior because they know they are being observed","A type of qualitative research design","A method of data coding"],ans:1,sec:"Research",marks:2},
  {q:"31. The age of the Earth is approximately:",opts:["4.5 billion years","4.5 million years","4.5 thousand years","4.5 trillion years"],ans:0,sec:"Research",marks:3},
  {q:"32. A researcher uses a questionnaire to collect data. This is an example of:",opts:["Quantitative data collection","Qualitative data collection","Experimental design","Observational research"],ans:0,sec:"Research",marks:3},
  {q:"33. The term 'Mens Rea' means:",opts:["The physical act of the crime","The guilty mind or intent","The punishment for the crime","The evidence in the case"],ans:1,sec:"Research",marks:3},
  {q:"34. A student scores 65 out of 80 in History and 75 out of 100 in Geography. What is his aggregate percentage?",opts:["75.0%","76.5%","77.7%","78.5%"],ans:2,sec:"Research",marks:3},
  {q:"35. Which of the following is a type of non-probability sampling?",opts:["Simple random sampling","Stratified sampling","Convenience sampling","Systematic sampling"],ans:2,sec:"Research",marks:3},
  {q:"36. The author of 'Malgudi Days' is:",opts:["R.K. Narayan","Mulk Raj Anand","Raja Rao","Vikram Seth"],ans:0,sec:"Research",marks:3},
  {q:"37. Identify the error in the sentence: \"The research team (A) along with the principal investigator (B) have submitted (C) the final report (D).\"",opts:["A","B","C","D"],ans:2,sec:"Research",marks:3},
  {q:"38. Which of the following is NOT a fundamental right under the Indian Constitution?",opts:["Right to Equality","Right to Freedom","Right to Property","Right against Exploitation"],ans:2,sec:"Research",marks:3},
  {q:"39. A qualitative research design typically involves:",opts:["Large sample sizes and statistical analysis","In-depth interviews and thematic analysis","Hypothesis testing with control groups","Numerical data collection"],ans:1,sec:"Research",marks:3},
  {q:"40. The currency of Japan is:",opts:["Yuan","Yen","Won","Dollar"],ans:1,sec:"Research",marks:3},
  {q:"41. In a row of 35 students, Ravi is 12th from the left. What is his rank from the right?",opts:["23rd","24th","25th","26th"],ans:1,sec:"Research",marks:4},
  {q:"42. The concept of 'Informed Consent' in research ethics means:",opts:["Participants are paid for their participation","Participants are fully informed about the study and voluntarily agree to participate","Participants are not told about the study's purpose","Participants are forced to participate for their own good"],ans:1,sec:"Research",marks:4},
  {q:"43. The planet known as the 'Red Planet' is:",opts:["Venus","Jupiter","Mars","Saturn"],ans:2,sec:"Research",marks:4},
  {q:"44. Which of the following is a measure of central tendency?",opts:["Standard deviation","Range","Mean","Variance"],ans:2,sec:"Research",marks:4},
  {q:"45. The 'Renaissance' period in European history is associated with:",opts:["The fall of the Roman Empire","The revival of art, culture, and learning","The Industrial Revolution","The French Revolution"],ans:1,sec:"Research",marks:4},
  {q:"46. A researcher wants to study the relationship between two variables. Which statistical test is most suitable for measuring the strength and direction of this relationship?",opts:["T-test","ANOVA","Pearson's correlation coefficient","Chi-square test"],ans:2,sec:"Research",marks:4},
  {q:"47. Choose the synonym of the word 'BENEVOLENT':",opts:["Malicious","Kind","Cruel","Hostile"],ans:1,sec:"Research",marks:4},
  {q:"48. The full form of DNA is:",opts:["Deoxyribonucleic Acid","Deoxynucleic Acid","Ribonucleic Acid","Deoxyribonuclear Acid"],ans:0,sec:"Research",marks:4},
  {q:"49. A shopkeeper sold an article for Rs. 500, incurring a loss of 20%. What was the cost price?",opts:["Rs. 580","Rs. 600","Rs. 620","Rs. 625"],ans:3,sec:"Research",marks:4},
  {q:"50. The 'Operational Definition' of a variable refers to:",opts:["The theoretical meaning of the variable","The specific way in which the variable is measured or manipulated in a study","The random error associated with the variable","The historical background of the variable"],ans:1,sec:"Research",marks:4},
],
};
